// PS4 libtorrent port — smoke test
// Links the ported libtorrent statically and initializes the engine.
#include <cstdio>
#include <torrent/torrent.h>
// PS4 kernel bootstrap
#include <orbis/libkernel.h>

// PS4 port: create-fself demands a module mapping for every undefined symbol.
// This weak TLS wrapper is auto-generated by the compiler for thread_local
// Thread::m_self; it is never called at runtime (plain pointer, no dynamic
// initializer), so a null-returning stub satisfies the link.
namespace torrent {
namespace system {
class Thread;
}
}
extern "C" __thread void* _ZTHN7torrent6system6Thread6m_selfE_ptr;
extern "C" void* _ZTHN7torrent6system6Thread6m_selfE() { return nullptr; }

int main() {
    std::printf("[ps4-torrent] boot\n");
    // initialize thread library + engine (exercises Poll::create() → epoll)
    torrent::initialize();
    std::printf("[ps4-torrent] engine initialized OK\n");
    torrent::cleanup();
    std::printf("[ps4-torrent] bye\n");
    return 0;
}
